#ifndef PINS_H
#define PINS_H

// motor pins

// left front
#define MOTOR_LEFT_FRONT_ENABLE 16
#define MOTOR_LEFT_FRONT_INPUT_1 17
#define MOTOR_LEFT_FRONT_INPUT_2 18

// left rear
#define MOTOR_LEFT_REAR_ENABLE 19
#define MOTOR_LEFT_REAR_INPUT_1 20
#define MOTOR_LEFT_REAR_INPUT_2 21

// right front
#define MOTOR_RIGHT_FRONT_ENABLE 15
#define MOTOR_RIGHT_FRONT_INPUT_1 14
#define MOTOR_RIGHT_FRONT_INPUT_2 13

// right rear
#define MOTOR_RIGHT_REAR_ENABLE 12
#define MOTOR_RIGHT_REAR_INPUT_1 11
#define MOTOR_RIGHT_REAR_INPUT_2 10

#endif // PINS_H
